trigger:
  branches:
    include:
      - main
      - developer
      - feature/*
      - release/*

resources:
  repositories:
    - repository: code
      type: git
      name: Devops/argo-code
      ref: refs/heads/main

stages:
  - template: base-argoit/dotnet/template.yml@code
    parameters:
      environment: ${{ values.environment }}
      dotNetVersion: '${{ values.dotnetVersion }}.x'
      tier: backend
      imageName: ${{ values.name }}
      updateHelmValuesEnabled: true
