apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: shield-platform
  namespace: argocd
spec:
  description: Shield platform workloads in hub cluster
  sourceRepos:
    - https://dev.azure.com/argosolutions/Root%20Cause/_git/poc-argo-gitops
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
