apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend-apps-manual-stg
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: sample-api
            namespace: sample-team
  template:
    metadata:
      name: "{{app}}-stg"
      labels:
        shield.env: stg
        shield.cluster: asgard
    spec:
      project: shield-backend
      source:
        repoURL: https://dev.azure.com/argosolutions/Root%20Cause/_git/poc-argo-gitops
        targetRevision: main
        path: "gitops/apps/backend/{{app}}/stg"
      destination:
        server: https://asgard.cluster.local
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true