trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
      - release/*

resources:
  repositories:
    - repository: argo-code
      type: git
      name: Root Cause/poc-argo-code
      ref: refs/heads/main

variables:
  - template: base-argoit/variables/global.yml@argo-code

stages:
  - template: base-argoit/python/template.yml@argo-code
    parameters:
      environment: ${{ variables.environment }}
